import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/common/Navbar";
import Sidebar from "@/components/common/Sidebar";
import ReduxProvider from "@/components/common/ReduxProvider";
import store from "@/hook/store";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "E-searchh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-white min-h-screen">
        <ReduxProvider>
          <div className="min-h-screen bg-white flex flex-col">
            <Navigation />
            <div className="flex flex-1">
              <Sidebar />
              <main className="flex-1 p-5">{children}</main>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
