import type { Metadata } from "next";
import localFont from "next/font/local";
import { Prompt } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/common/Navbar";
import Sidebar from "@/components/common/Sidebar";
import ReduxProvider from "@/components/common/ReduxProvider";

// Uncomment and adjust Geist fonts if needed
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "E-searchh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${prompt.variable}`}>
      <body className="bg-white h-screen">
        <ReduxProvider>
          <div className="h-screen bg-white flex flex-col">
            <Navigation />
            <div className="flex flex-1 h-screen">
              <Sidebar />
              <main className={`flex-1 ${prompt.className}`}>{children}</main>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
