import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/common/Navbar";
import Sidebar from "@/components/common/Sidebar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "E-searchh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <body className="bg-white min-h-screen">
        <div className="min-h-screen bg-white flex flex-col">
          {/* Navigation Bar at the top */}
          <Navigation />

          {/* Sidebar and main content container */}
          <div className="flex flex-1">
            <Sidebar/>

            {/* Main content area */}
            <main className="flex-1 p-5">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
