http:
  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes: ["/adminer"]
  routers:
    dashboard:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: "api@internal"
      entryPoints:
        - "dashboard"

    next-private:
      rule: "Host(`cp24nk1.sit.kmutt.ac.th`)"
      service: next
      entryPoints:
        - "web"

    next-public:
      rule: "Host(`capstone24.sit.kmutt.ac.th`)"
      service: next
      entryPoints:
        - "web"
