http:
  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes: ["/adminer"]
  routers:
    dashboard:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: "api@internal"
      entryPoints:
        - "dashboard"
