services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - next
    networks:
      - my_network

  db:
    container_name: db
    image: postgres:15.5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5173:5432"
    networks:
      - my_network
    volumes:
      - db:/var/lib/postgresql/data/

  django:
    container_name: django
    build:
      context: backend
      dockerfile: Dockerfile.Dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    user: "1000:1000"
    depends_on:
      - db
    networks:
      - my_network
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: postgres
      SQL_USER: root
      SQL_PASSWORD: dbpass
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    command: "python manage.py runserver 0.0.0.0:8080"

  next:
    build:
      context: ./Front-end/react-nginx
    ports:
      - "3000:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db:
    driver: local
