FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./source/requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install gunicorn dj-database-url psycopg2-binary

COPY ./source .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "CAPSTONE_PROJECT.wsgi"]