# Generated by Django 4.2.16 on 2024-11-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45)),
                ('category_detail', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfvanue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=45)),
                ('type_description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='VenueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('min_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('parking_space', models.IntegerField()),
                ('additional_information', models.TextField()),
                ('venue_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('typeOfvanue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.typeofvanue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venue_approval', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=45)),
                ('datetime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.account')),
                ('venue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venuerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('min_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('parking_space', models.IntegerField()),
                ('additional_information', models.TextField()),
                ('venue_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('typeOfvanue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.typeofvanue')),
                ('venue_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.venuerequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=45)),
                ('province', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('sub_district', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.account')),
            ],
        ),
        migrations.CreateModel(
            name='RoleHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.role')),
            ],
        ),
        migrations.CreateModel(
            name='EvnetOfVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryOfEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.categoryofevent')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venue')),
                ('venue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venuerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_booking', models.CharField(max_length=45)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.account')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venue')),
            ],
        ),
    ]
