# Generated by Django 4.2.16 on 2024-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfvanue',
            new_name='TypeOfVenue',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='personal_certification',
            new_name='personal_identification',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='typeOfvanue',
            new_name='type_of_venue',
        ),
        migrations.RenameField(
            model_name='venuerequest',
            old_name='personal_certification',
            new_name='personal_identification',
        ),
        migrations.RenameField(
            model_name='venuerequest',
            old_name='typeOfvanue',
            new_name='type_of_venue',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='min_capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_request',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='min_capacity',
        ),
        migrations.AddField(
            model_name='venue',
            name='area_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='outdoor_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='area_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='outdoor_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='venue_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='parking_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venuerequest',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuerequest',
            name='parking_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuerequest',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuerequest',
            name='venue_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
