# Generated by Django 4.2.16 on 2024-11-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_typeofvanue_typeofvenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='type_of_venue',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='type_of_venue',
        ),
    ]
