# Generated by Django 4.2.16 on 2024-11-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_venue_type_of_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_booking',
        ),
        migrations.CreateModel(
            name='StatusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.booking')),
            ],
        ),
    ]
