# Generated by Django 4.2.16 on 2024-11-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_booking_id_booking_statusbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusbooking',
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='statusbooking',
            name='status_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='status_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.statusbooking'),
        ),
        migrations.AddField(
            model_name='statusbooking',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statusbooking',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
