# Generated by Django 4.2.16 on 2024-11-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_statusbooking_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account',
        ),
    ]
