# Generated by Django 4.2.16 on 2024-11-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_account_groups_remove_account_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofvenue',
            name='type_description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='typeofvenue',
            name='type_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue'),
        ),
        migrations.AlterField(
            model_name='venuerequest',
            name='venue_type',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue'),
        ),
    ]
