# Generated by Django 4.2.16 on 2024-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_typeofvenue_type_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofvenue',
            name='type_description',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='typeofvenue',
            name='type_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
