# Generated by Django 4.2.16 on 2024-11-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_typeofvenue_type_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuerequest',
            name='venue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue'),
        ),
    ]
