# Generated by Django 4.2.16 on 2024-11-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_venuerequest_venue_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='category',
            new_name='category_event',
        ),
        migrations.RenameField(
            model_name='venuerequest',
            old_name='category',
            new_name='category_event',
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.account'),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='venue_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.account'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue'),
        ),
    ]
