# Generated by Django 4.2.16 on 2025-01-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_rename_category_venue_category_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='user_name',
        ),
    ]
