# Generated by Django 4.2.16 on 2025-01-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_rename_username_account_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_name',
            new_name='username',
        ),
    ]
