# Generated by Django 4.2.16 on 2025-01-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_rename_user_name_account_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvnetOfVenue',
            new_name='EventOfVenue',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewDetail', models.TextField()),
                ('createAt', models.DateTimeField()),
                ('point', models.IntegerField()),
                ('review_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.account')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venue')),
            ],
        ),
    ]
