# Generated by Django 4.2.16 on 2025-01-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_rename_evnetofvenue_eventofvenue_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_owner',
            new_name='account',
        ),
    ]
