# Generated by Django 4.2.16 on 2025-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_rename_review_owner_review_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
