# Generated by Django 4.2.16 on 2025-01-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_remove_rolehaspermission_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='role',
            new_name='role_id',
        ),
    ]
