# Generated by Django 4.2.16 on 2025-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_rename_role_account_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='personal_identification',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_certification',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
