# Generated by Django 4.2.16 on 2025-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_venue_personal_identification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuerequest',
            name='personal_identification',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='venuerequest',
            name='venue_certification',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
