# Generated by Django 4.2.16 on 2025-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
