# Generated by Django 4.2.16 on 2025-01-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_notifications_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='eventofvenue',
            name='CategoryOfEvent',
        ),
        migrations.RemoveField(
            model_name='eventofvenue',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='eventofvenue',
            name='venue_request',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='review',
            name='account',
        ),
        migrations.RemoveField(
            model_name='review',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='account',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_owner',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_type',
        ),
        migrations.RemoveField(
            model_name='venueapproval',
            name='account',
        ),
        migrations.RemoveField(
            model_name='venueapproval',
            name='venue_request',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='venue_owner',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='venue_type',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CategoryOfEvent',
        ),
        migrations.DeleteModel(
            name='EventOfVenue',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='StatusBooking',
        ),
        migrations.DeleteModel(
            name='TypeOfVenue',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueApproval',
        ),
        migrations.DeleteModel(
            name='VenueRequest',
        ),
    ]
