# Generated by Django 4.2.16 on 2025-01-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0027_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='account',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
