# Generated by Django 4.2.16 on 2025-01-27 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0028_remove_userdetail_account_userdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45)),
                ('category_detail', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EventOfVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryOfEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.categoryofevent')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_type', models.CharField(max_length=45)),
                ('create_at', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewDetail', models.TextField()),
                ('createAt', models.DateTimeField()),
                ('point', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=45, null=True)),
                ('type_description', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('category_event', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('area_size', models.CharField(blank=True, max_length=5, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('parking_space', models.IntegerField(blank=True, null=True)),
                ('outdoor_spaces', models.IntegerField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('venue_certification', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('personal_identification', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('venue_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venue_approval', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=45)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('category_event', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('area_size', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('parking_space', models.IntegerField(blank=True, null=True)),
                ('outdoor_spaces', models.IntegerField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('venue_certification', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('personal_identification', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('venue_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='venueapproval',
            name='venue_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venuerequest'),
        ),
        migrations.AddField(
            model_name='review',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venue'),
        ),
        migrations.AddField(
            model_name='eventofvenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venue'),
        ),
        migrations.AddField(
            model_name='eventofvenue',
            name='venue_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.venuerequest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.statusbooking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venue'),
        ),
    ]
