# Generated by Django 4.2.16 on 2025-01-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_booking_categoryofevent_eventofvenue_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuerequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.statusbooking'),
        ),
    ]
