# Generated by Django 4.2.16 on 2025-01-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_venuerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='venue_owner',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='venue_type',
        ),
        migrations.RemoveField(
            model_name='eventofvenue',
            name='venue_request',
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.statusbooking'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='area_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='VenueApproval',
        ),
        migrations.DeleteModel(
            name='VenueRequest',
        ),
    ]
