# Generated by Django 4.2.17 on 2025-01-31 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0031_remove_venuerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.booking'),
        ),
        migrations.CreateModel(
            name='VenueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('category_event', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('area_size', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('parking_space', models.IntegerField(blank=True, null=True)),
                ('outdoor_spaces', models.IntegerField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('venue_certification', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('personal_identification', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.statusbooking')),
                ('venue_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.typeofvenue')),
            ],
        ),
    ]
