# Generated by Django 4.2.16 on 2025-02-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_venuerequest_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofvenue',
            name='venue_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venuerequest'),
        ),
        migrations.AlterField(
            model_name='eventofvenue',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.venue'),
        ),
    ]
