# Generated by Django 4.2.17 on 2025-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_userdetail_address_alter_userdetail_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
