# Generated by Django 4.2.17 on 2025-02-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_notifications_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isReview',
            field=models.BooleanField(default=False),
        ),
    ]
