# Generated by Django 4.2.17 on 2025-02-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_booking_isreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Booking',
            new_name='booking',
        ),
    ]
