# Generated by Django 4.2.16 on 2025-02-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_favoritevenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_image',
        ),
    ]
