# Generated by Django 4.2.16 on 2025-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.FileField(blank=True, null=True, upload_to='images/reviews/'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='images/reviews/'),
        ),
    ]
