# Generated by Django 4.2.16 on 2025-02-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_review_review_image_alter_reviewimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_image',
        ),
    ]
