# Generated by Django 4.2.17 on 2025-03-12 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_alter_reviewimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/reviews/'),
            preserve_default=False,
        ),
    ]
