# Generated by Django 4.2.16 on 2025-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_remove_review_point_review_matches_expectations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Matches_expectations',
        ),
        migrations.RemoveField(
            model_name='review',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='review',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value_for_money',
        ),
        migrations.AddField(
            model_name='review',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
