# Generated by Django 4.2.16 on 2025-03-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_rename_point_review_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Matches_expectations',
            new_name='matches_expectations',
        ),
    ]
