# Generated by Django 4.2.16 on 2025-03-12 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0053_rename_matches_expectations_review_matches_expectations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
