# Generated by Django 4.2.16 on 2025-03-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0054_alter_review_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/venues/')),
                ('venue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='event.venuerequest')),
            ],
        ),
    ]
