# Generated by Django 4.2.16 on 2025-03-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0055_venuerequestfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='image',
        ),
    ]
