# Generated by Django 4.2.17 on 2025-03-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0056_remove_venue_image_remove_venuerequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_images', to='event.venue'),
        ),
    ]
