# Generated by Django 4.2.16 on 2025-03-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0057_alter_venueimage_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/venues/'),
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
