# Generated by Django 4.2.16 on 2025-03-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0058_venue_images_delete_venueimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='images',
            new_name='venue_images',
        ),
    ]
