# Generated by Django 4.2.16 on 2025-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0059_rename_images_venue_venue_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/venues/'),
        ),
        migrations.DeleteModel(
            name='VenueRequestImage',
        ),
    ]
