# Generated by Django 4.2.16 on 2025-03-16 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0060_venuerequest_image_delete_venuerequestimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_images',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='image',
        ),
        migrations.CreateModel(
            name='VenueRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/venues/')),
                ('venue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.venuerequest')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/venues/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_images', to='event.venue')),
            ],
        ),
    ]
