# Generated by Django 4.2.16 on 2025-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0061_remove_venue_venue_images_remove_venuerequest_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/venues/'),
        ),
        migrations.AddField(
            model_name='venuerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/venues/'),
        ),
    ]
