# Generated by Django 4.2.16 on 2025-03-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0062_venue_image_venuerequest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        ),
    ]
