# Generated by Django 4.2.16 on 2025-03-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0063_remove_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuerequest',
            name='image',
        ),
    ]
