# Generated by Django 4.2.16 on 2025-03-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0064_remove_venuerequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuerequestimage',
            name='venue_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venueRequest_images', to='event.venuerequest'),
        ),
    ]
