# Generated by Django 4.2.16 on 2025-03-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0067_alter_venuerequestimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuerequestimage',
            name='image',
            field=models.ImageField(upload_to='images/venue_Requests/'),
        ),
    ]
