# Generated by Django 4.2.20 on 2025-03-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0070_venue_latitude_venue_longitude_venuerequest_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_event', models.CharField(blank=True, max_length=50, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_category', to='event.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueRequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_event', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='venuerequestfile',
            name='venue_request',
        ),
        migrations.RemoveField(
            model_name='venuerequest',
            name='category_event',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='VenueFile',
        ),
        migrations.DeleteModel(
            name='VenueRequestFile',
        ),
        migrations.AddField(
            model_name='venuerequestcategory',
            name='venue_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venueRequest_category', to='event.venuerequest'),
        ),
    ]
