# Generated by Django 4.2.20 on 2025-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0071_venuecategory_venuerequestcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='interest',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
