# Generated by Django 4.2.20 on 2025-03-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0072_userdetail_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.CharField(blank=True, max_length=45, null=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventofvenue',
            name='CategoryOfEvent',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest',
        ),
        migrations.DeleteModel(
            name='CategoryOfEvent',
        ),
    ]
