# Generated by Django 4.2.20 on 2025-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0074_userdetail_interested_delete_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='interested_check',
            field=models.BooleanField(default=False),
        ),
    ]
