# Generated by Django 4.2.20 on 2025-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0075_userdetail_interested_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='interested_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
