# Generated by Django 4.2.20 on 2025-03-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0076_alter_userdetail_interested_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='category_event',
        ),
    ]
