name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: cp24nk1.sit.kmutt.ac.th
        username: sysadmin
        key: d2cWx5PtTf63pP
        script: |
          cd /capstoneProject/Capstone_Project
          
          git pull origin main
          
          docker compose down
          
          docker compose up -d --build

          docker image prune -af
