name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: cp24nk1.sit.kmutt.ac.th
        username: sysadmin
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBRjRaS7uZ5kFLFZXdwoM+t+cx0A4iK+GyhO5Qt4t9cpgAAAJiqUyrvqlMq7wAAAAtzc2gtZWQyNTUxOQAAACBRjRaS7uZ5kFLFZXdwoM+t+cx0A4iK+GyhO5Qt4t9cpgAAAED0AmBXQP2acJObAgDhwBVu9rY6dPk0PrvexYP7bdZhVlGNFpLu5nmQUsVld3Cgz635zHQDiIr4bKE7lC3i31ymAAAAFW9hdF9vYXQxOUBob3RtYWlsLmNvbQ==
        script: |
          cd /capstoneProject/Capstone_Project
          
          git pull origin main
          
          docker compose down
          
          docker compose up -d --build

          docker image prune -af
